// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgwRyr8YCc3waAeAS-TPrTs6fn9ubSQOw',
    appId: '1:941634018910:web:c252fcb47a6d8b69881ecf',
    messagingSenderId: '941634018910',
    projectId: 'project-chat-22c87',
    authDomain: 'project-chat-22c87.firebaseapp.com',
    storageBucket: 'project-chat-22c87.firebasestorage.app',
    measurementId: 'G-74LQTH3LD7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC18I-hiflMKEB3qdyDWKzYs1VYhZ13RS8',
    appId: '1:941634018910:android:c49ae9493920fda8881ecf',
    messagingSenderId: '941634018910',
    projectId: 'project-chat-22c87',
    storageBucket: 'project-chat-22c87.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATBQAY2OvRFqd599LD6FT92bI0GvN8o9c',
    appId: '1:941634018910:ios:9ce8224bfdc506a6881ecf',
    messagingSenderId: '941634018910',
    projectId: 'project-chat-22c87',
    storageBucket: 'project-chat-22c87.firebasestorage.app',
    iosBundleId: 'com.example.projectChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATBQAY2OvRFqd599LD6FT92bI0GvN8o9c',
    appId: '1:941634018910:ios:9ce8224bfdc506a6881ecf',
    messagingSenderId: '941634018910',
    projectId: 'project-chat-22c87',
    storageBucket: 'project-chat-22c87.firebasestorage.app',
    iosBundleId: 'com.example.projectChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDgwRyr8YCc3waAeAS-TPrTs6fn9ubSQOw',
    appId: '1:941634018910:web:bb02a1f7dd8c7991881ecf',
    messagingSenderId: '941634018910',
    projectId: 'project-chat-22c87',
    authDomain: 'project-chat-22c87.firebaseapp.com',
    storageBucket: 'project-chat-22c87.firebasestorage.app',
    measurementId: 'G-4N8WE9602X',
  );
}
